# Generated by Django 5.1.2 on 2024-11-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttable',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
