# Generated by Django 5.1.2 on 2024-11-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side_app', '0003_whishlisttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttable',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
