# Generated by Django 5.1.2 on 2024-12-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side_app', '0004_alter_carttable_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttable',
            name='session_is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whishlisttable',
            name='session_is_available',
            field=models.BooleanField(default=True),
        ),
    ]
