"""
Django settings for project_book project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1g49tox43m2=lpvi(b7%51zpccv%vg!_f2zukzu_n)3ccmet&0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #google auth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    # Optional -- requires install using `django-allauth[socialaccount]`.
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    #payment 
    'paypal.standard.ipn',
    

    # apps
    'log_reg_app',
    'adminside_app',
    'user_side_app',
    'user_profile_app',
    'order_detail_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'log_reg_app.custom_middleware.AccessControlMiddleware',
    'user_side_app.custom_middleware.UserAccessControlMiddleware',
    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'project_book.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR / 'templates',)],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'user_side_app.context_processors.list_items',
                # `allauth` needs this from django
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_book.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'book_project',
        'USER': 'book_owner',
        'PASSWORD': '11421',
        'HOST': 'localhost',  # or the IP address of your database server
        'PORT': '5433',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOGIN_URL = '/admin_login/'

AUTH_USER_MODEL = 'log_reg_app.UserTable'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default backend
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'assets'),
]

STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# In your settings.py for development
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jubink76@gmail.com'
EMAIL_HOST_PASSWORD = 'hdvvwrwgkadrpjcl'


ACCOUNT_EMAIL_VERIFICATION = "none"  # Avoids email verification redirect issues
ACCOUNT_SIGNUP_REDIRECT_URL = 'homepage_after_login'  # Redirect after signup
SOCIALACCOUNT_AUTO_SIGNUP = True  # Disables the need for manual signup after social login


SITE_ID = 1
AUTHENTICATION_BACKENDS = [

    'django.contrib.auth.backends.ModelBackend',

    'allauth.account.auth_backends.AuthenticationBackend',

]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}
SIGNUP_REDIRECT_URL = '/'

LOGIN_REDIRECT_URL = 'homepage_after_login'
ACCOUNT_LOGOUT_REDIRECT_URL = 'homepage_before_login'

# Keep session data for 7 days
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7
# Session data is kept on the server side even if the browser session is closed
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

RAZORPAY_KEY_ID = 'rzp_test_COptAFlNCi9Fdi'
RAZORPAY_KEY_SECRET = 'sZNZcjvDRenuZqD45113Rstu'


# PAYPAL_MODE = "sandbox"  # Change to "live" for production
# PAYPAL_CLIENT_ID = "AX92J9UuypZLnwqtgakDAcNj_iN0-ZBgE6VKF_va7SXlMP0HxQULMTZmhlgBw1bQpaFazhtyXnaDLNFn"
# PAYPAL_CLIENT_SECRET = "EGRH5H_j9uO9InlsbzORSvwQh9IecikRjK1CtSvHrpJpCwFih0t-DBWmEP764ZSM8LuSoyeirXgrUCdS"
PAYPAL_CLIENT_ID = 'Ab49v3vyytYGhK6E-FIJh8qUfQqmZRuH4nNiNjvxJrZiD7yGXXe2VAQ_w0YRhFqjYezMx1A0DyrkNoWs' 
PAYPAL_CLIENT_SECRET = 'EBNicjhxbNeCn-tQ4uZ7-yI-9efwtPBucVbnJYP0Er8BEqe9mkTeiC1nqjBkyyu1ggAo-QSYaEIob9AM'
PAYPAL_MODE = 'sandbox'




# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#         '__main__': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#     },
# }

