# Generated by Django 5.1.2 on 2024-11-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_detail_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
