# Generated by Django 5.1.2 on 2024-11-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_detail_app', '0002_alter_orderdetails_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order_id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
