# Generated by Django 5.1.2 on 2024-11-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_detail_app', '0004_alter_orderdetails_order_id_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
