# Generated by Django 5.1.2 on 2024-11-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_detail_app', '0006_orderitem_order_alter_coupontable_coupon_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
