# Generated by Django 5.1.2 on 2024-11-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_detail_app', '0012_orderdetails_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupontable',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupontable',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupontable',
            name='min_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupontable',
            name='coupon_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Vat Amount')], default='percentage', max_length=20),
        ),
    ]
