# Generated by Django 5.1.2 on 2024-11-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_detail_app', '0013_coupontable_discount_value_coupontable_max_uses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offertable',
            old_name='name',
            new_name='offer_name',
        ),
        migrations.AddField(
            model_name='offertable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offertable',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('bogo', 'Buy One Get One'), ('bundle', 'Bundle Discount')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offertable',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offertable',
            name='offer_type',
            field=models.CharField(choices=[('category', 'Category Offer'), ('product', 'Single Product Offer'), ('special', 'Special Day Offer'), ('seasonal', 'Seasonal Offer')], max_length=20),
        ),
    ]
