# Generated by Django 5.1.2 on 2024-11-29 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0008_booktable_offer_price'),
        ('order_detail_app', '0014_rename_name_offertable_offer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offertable',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside_app.categorytable'),
        ),
        migrations.AddField(
            model_name='offertable',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside_app.booktable'),
        ),
    ]
