# Generated by Django 5.1.2 on 2024-11-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_detail_app', '0015_offertable_category_offertable_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupontable',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
