# Generated by Django 5.1.2 on 2024-12-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_detail_app', '0016_alter_coupontable_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertable',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
