# Generated by Django 5.1.2 on 2024-12-02 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0008_booktable_offer_price'),
        ('order_detail_app', '0017_alter_offertable_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertable',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_offers', to='adminside_app.categorytable'),
        ),
    ]
