# Generated by Django 5.1.2 on 2024-12-04 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0008_booktable_offer_price'),
        ('order_detail_app', '0018_alter_offertable_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertable',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offer', to='adminside_app.booktable'),
        ),
    ]
