# Generated by Django 5.1.2 on 2024-12-09 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_detail_app', '0025_reviewtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtable',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_detail_app.orderdetails'),
        ),
    ]
