# Generated by Django 5.1.2 on 2024-12-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_detail_app', '0026_reviewtable_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewtable',
            name='book',
        ),
    ]
