# Generated by Django 5.1.2 on 2024-12-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_detail_app', '0028_orderdetails_is_returned_orderitem_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('Out of delivery', 'Out of delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Out of delivery', 'Out of delivery'), ('Canceled', 'Canceled'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
