# Generated by Django 5.1.2 on 2024-11-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0006_alter_author_name_alter_bookimage_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='booktable',
            name='vat_amount',
        ),
    ]
