# Generated by Django 5.1.2 on 2024-11-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0007_rename_price_booktable_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
