# Generated by Django 5.1.2 on 2024-12-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0008_booktable_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='additonal_offer_applied',
            field=models.BooleanField(default=False),
        ),
    ]
