# Generated by Django 5.1.2 on 2024-12-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0009_booktable_additonal_offer_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='additonal_offer_applied',
            new_name='additional_offer_applied',
        ),
    ]
