# Generated by Django 5.1.2 on 2024-12-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0010_rename_additonal_offer_applied_booktable_additional_offer_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='previous_offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
