# Generated by Django 5.1.2 on 2024-12-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0011_booktable_previous_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='previous_offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
