# Generated by Django 5.1.2 on 2024-12-07 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0012_alter_booktable_previous_offer_price'),
        ('order_detail_app', '0024_returnrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='applied_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_books', to='order_detail_app.offertable'),
        ),
    ]
