from django.urls import path
from . import views
urlpatterns = [
    path('admin_dashboard/',views.admin_dashboard, name='admin_dashboard'),
    path('admin_users/',views.admin_users,name='admin_users'), 
    path('add_users/',views.add_users, name='add_users'),
    path('view_users/<int:pk>',views.view_users, name='view_users'),
    path('admin_category/',views.admin_category, name='admin_category'),
    path('add_category/',views.add_category, name='add_category'),
    path('edit_category/<int:pk>',views.edit_category, name='edit_category'),
    path('delete_category/<int:pk>',views.delete_category, name='delete_category'),
    path('admin_products/',views.admin_products, name='admin_products'),
    path('add_products/',views.add_products, name='add_products'),
    path('view_product/<int:pk>',views.view_product, name='view_product'),
    path('edit_product/<int:pk>',views.edit_product,name='edit_product'),
    path('delete_product/<int:pk>',views.delete_product,name='delete_product'),
    path('admin_orders/',views.admin_orders, name='admin_orders'),
    path('view_order/<str:order_id>/',views.view_order, name='view_order'),
    path('update_order/<str:order_id>/',views.update_order, name='update_order'),
    path('admin_cancel_order/<str:order_id>/', views.admin_cancel_order, name='admin_cancel_order'),
    path('admin_single_item_cancel/<str:order_id>/item/<int:order_item_id>/cancel/', views.admin_single_item_cancel, name='admin_single_item_cancel'),
    path('order_status_update/<str:order_id>/',views.status_update, name='order_status_update'),
    path('admin_coupon/', views.admin_coupon, name='admin_coupon'),
    path('admin_coupon/<int:coupon_id>/', views.admin_coupon, name='admin_coupon_edit'),
    path('admin_coupon/delete/<int:coupon_id>/', views.delete_coupon, name='delete_coupon'),
    path('admin_offer',views.admin_offer,name='admin_offer'),
    path('add_category_offer/<int:category_id>/',views.add_category_offer,name='add_category_offer'),
    path('edit_category_offer/<int:category_id>/', views.edit_category_offer, name='edit_category_offer'),
    path('delete_category_offer/<int:category_id>/', views.delete_category_offer, name='delete_category_offer'),
    path('add_product_offer/<int:product_id>/',views.add_product_offer,name='add_product_offer'),
    path('edit_product_offer/<int:product_id>/',views.edit_product_offer,name='edit_product_offer'),
    path('delete_product_offer/<int:product_id>/',views.delete_product_offer,name='delete_product_offer'),
    path('admin_coupon/get_coupon_details/<int:coupon_id>/', views.get_coupon_details, name='get_coupon_details'),
    path('sales-report/pdf/', views.generate_detailed_sales_report_pdf, name='generate_detailed_sales_report_pdf'),
    path('sales-report/excel/', views.generate_detailed_sales_report_excel, name='generate_detailed_sales_report_excel'),
    path('return_requests',views.return_requests,name='return_requests'),
    
]
