# Generated by Django 5.1.2 on 2024-11-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('building_no', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('address_phone', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Address Table',
            },
        ),
    ]
