# Generated by Django 5.1.2 on 2024-11-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0002_addresstable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresstable',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
