# Generated by Django 5.1.2 on 2024-11-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0004_alter_addresstable_options_alter_addresstable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresstable',
            name='address_type',
            field=models.CharField(choices=[('home', 'home'), ('office', 'office')], default='home', max_length=20),
        ),
    ]
