# Generated by Django 5.1.2 on 2024-12-04 04:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0006_wallettable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettable',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wallettable',
            name='transaction_amount',
        ),
        migrations.RemoveField(
            model_name='wallettable',
            name='transaction_time',
        ),
        migrations.RemoveField(
            model_name='wallettable',
            name='transaction_type',
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('add', 'Added to wallet'), ('deduct', 'Deducted from wallet'), ('refund', 'Refunded')], max_length=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user_profile_app.wallettable')),
            ],
        ),
    ]
